services:
  api:
   build:
     context: .
   ports:
     - "8000:8000"
   volumes:
     - ./src/:/api/src/
  db:
   image: postgres:16.3
   environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres 

